baseURL = "https://antgarsil.github.io/"
title = "Antgarsil Pages"
theme = "hello-friend-ng"
languagecode = "en"
defaultcontentlanguage = "en"

enableRobotsTXT = true
googleanalytics = "UA-127742617-1"

[pagination]
pagerSize = 20

[markup.highlight]
style = "github-dark"

[[menu.main]]
	name = "Home"
	url = "/"
	weight = "10"
[[menu.main]]
	name = "Blog"
	url ="posts"
	weight = "20"

[params]
	author = "Anton Garcia Dosil"
	info = "Antgarsil Pages"
	profilePicture = "images/avatar.png"	
	homeSubtitle = """I break things
	Anton's personal website and blog"""
	enableSharingButtons = true
	keywords = "security,pentesting,pentest,penetration testing"

[[params.social]]
	name = "github"
	icon = "github"
	weight = 1
	url = "https://github.com/antgarsil"
[[params.social]]
	name = "X"
	icon = "X"
	weight = 2
	url = "https://x.com/agdosil"
[[params.social]]
	name = "linkedin"
	icon = "linkedin"
	weight = 3
	url = "https://www.linkedin.com/in/antongarciadosil/"
[[params.social]]
	name = "mastodon"
	icon = "mastodon"
	weight = 4
	url = "https://infosec.exchange/@agdosil"
